version: '3.4'
services:
  web:
    image: webdevops/php-nginx:7.3
#    build:
#      context: .
#      dockerfile: Dockerfile
    container_name: web
    env_file: .env
    environment:
      - APP_ENV=dev
      - PHP_DATE_TIMEZONE=Asia/Shanghai
    restart: always
    ports:
      - "80:80"
    volumes:
      - .:/app/
      - ./ci/nginx.conf:/opt/docker/etc/nginx/vhost.conf
#    stdin_open: true
#    tty: true
#    command: /bin/bash
    command: >
      sh -c "sh /app/start.sh"
    networks:
      - prod-network
networks:
  prod-network:
    external: true


